### ISSUE TITLE
World server equipment save crash due to missing hubSpec

### ISSUE THREAD

**Issue by avaer** [exokitxr/zeo#51]
https://github.com/modulesio/zeo/blob/21fa0a5a8edecf6fe5282f3f28dbcb5c575ee00e/core/engines/world/server.js#L279
https://github.com/modulesio/zeo/blob/21fa0a5a8edecf6fe5282f3f28dbcb5c575ee00e/core/engines/world/server.js#L136

**Comment by avaer** [comment]
Stack dump

```
TypeError: Cannot read property 'host' of null
    at Promise (/home/k/zeo/installed/plugins/node_modules/world/server.js:136:38)
    at _requestHub (/home/k/zeo/installed/plugins/node_modules/world/server.js:133:78)
    at next (/home/k/zeo/installed/plugins/node_modules/world/server.js:295:31)
    at _go (/home/k/zeo/installed/plugins/node_modules/world/server.js:788:7)
    at WebSocket.c.on.s (/home/k/zeo/installed/plugins/node_modules/world/server.js:491:39)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:192:7)
    at Receiver._receiver.onmessage (/home/k/zeo/node_modules/ws/lib/WebSocket.js:143:54)
    at Receiver.dataMessage (/home/k/zeo/node_modules/ws/lib/Receiver.js:375:14)
    at extension.decompress (/home/k/zeo/node_modules/ws/lib/Receiver.js:344:40)
```

**Comment by avaer** [comment]
Still an issue.
