### ISSUE TITLE
Bullet physics engine crash when demoing mc plugin

### ISSUE THREAD

**Issue by avaer** [exokitxr/zeo#71]
```
TypeError: Cannot set property 'matrix' of null                                            
    at WebSocket.c.on.s (/home/k/zeo/installed/plugins/node_modules/world/server.js:425:55)
    at emitTwo (events.js:106:13)                                                                                                                                                 
    at WebSocket.emit (events.js:192:7)                                                                                                                                           
    at Receiver._receiver.onmessage (/home/k/zeo/node_modules/ws/lib/WebSocket.js:143:54)                                                                                         
    at Receiver.dataMessage (/home/k/zeo/node_modules/ws/lib/Receiver.js:375:14)                                                                                                  
    at extension.decompress (/home/k/zeo/node_modules/ws/lib/Receiver.js:344:40)                                                                                                  
    at _inflate.flush (/home/k/zeo/node_modules/ws/lib/PerMessageDeflate.js:279:12)                                                                                               
    at afterWrite (_stream_writable.js:383:3)                                                                                                                                     
    at onwrite (_stream_writable.js:374:7)                                                                                                                                        
    at afterTransform (_stream_transform.js:79:3)                                                                                                                                 
    at TransformState.afterTransform (_stream_transform.js:54:12)
```

Looks like some object isn't being tracked on the backend correctly.

**Comment by avaer** [comment]
It could just be the fact that I was working on remote tag meshes refactoring at the time.

**Comment by avaer** [comment]
Yeah, I think this was because of grabbing/ungrabbing with bad synchronization -- controllers were picked up incorrectly by two tabs at once.

Will re-open if I see it again.
