### ISSUE TITLE
Bullet physics build failing

### ISSUE THREAD

**Issue by avaer** [exokitxr/zeo#72]
`debian jessie`

https://gist.github.com/ibrahimduran/d06115880041762a0663c6406f86e03f

```
In file included from ../src/world.cpp:1:0:
../inc/helper.h:51:27: warning: backslash-newline at end of file
 #define MOXCHK(condition) \
 ^
  SOLINK_MODULE(target) Release/obj.target/physics.node
g++: error: /home/ibrah/Projects/vr/node_modules/zeo/core/engines/bullet/bullet3/build/src/BulletDynamics/libBulletDynamics.a: No such file or directory
g++: error: /home/ibrah/Projects/vr/node_modules/zeo/core/engines/bullet/bullet3/build/src/BulletCollision/libBulletCollision.a: No such file or directory
g++: error: /home/ibrah/Projects/vr/node_modules/zeo/core/engines/bullet/bullet3/build/src/LinearMath/libLinearMath.a: No such file or directory
physics.target.mk:134: recipe for target 'Release/obj.target/physics.node' failed
make: *** [Release/obj.target/physics.node] Error 1
make: Leaving directory '/home/ibrah/Projects/vr/node_modules/zeo/core/engines/bullet/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ibrah/Projects/vr/node_modules/zeo/core/engines/bullet/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:192:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

Was ultimately fixed by going into `core/engines/bullet/bullet3` and doing manual `build.sh` from there.

**Comment by avaer** [comment]
Apparently there was no cancellation of the initial build, no errors, and no build. It just didn't go into the `bullet3` directory to do the build via `bullet3/build.sh`.

**Comment by avaer** [comment]
Fixed, it was actually differences in dependent modules install locations that were referenced from a relative path in the bullet engine.
