### ISSUE TITLE
EPIPE error handling

### ISSUE THREAD

**Issue by avaer** [exokitxr/zeo#81]
```
https://insecure.zeovr.io:8000/?username=username&password=password
commonjs-proxy:/home/k/zeo/installed/plugins/node_modules/three/node_modules/three/build/three.module.js (1:169) 'default' is not exported by 'installed/plugins/node_modules/thre
e/node_modules/three/build/three.module.js'
commonjs-proxy:/home/k/zeo/installed/plugins/node_modules/three/node_modules/three/build/three.module.js (1:169) 'default' is not exported by 'installed/plugins/node_modules/thre
e/node_modules/three/build/three.module.js'
events.js:161
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1028:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:804:14)
```

**Comment by avaer** [comment]
This is not only related to any particular plugin, the repro is to simply refresh the page a lot.
